# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CountryCodePickerSwiftExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountryCodePickerSwiftExample
  
  pod 'CountryCodePickerSwift', :path => "../CountryCodePickerSwift/"


  target 'CountryCodePickerSwiftExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountryCodePickerSwiftExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
